; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = Src
include_dir = Inc

[env]
platform = ststm32
board = disco_f072rb
framework = stm32cube

[env:bt_conf]
build_flags = -DCP1
[env:magnetic_encoder]
build_flags = -DMENC
[env:bluetooth_magenc]
build_flags = -DBTENC
[env:motor]
build_flags = -DMTR
[env:bt_mag_serial]
build_flags = -DBTENCSER
[env:lab6]
build_flags = -DLAB6
[env:project_main]
build_flags = -DPROJMAIN
[env:test]
build_flags = -DTEST